### PR TITLE
fix: set cookie `secure=True` attribute

### PR DESCRIPTION
**Pull request by patheard**
# Summary
Update the cookie so that it can no longer sent in plaintext with unecrypted requests.

# Related
- cds-snc/security-risk-register#147

### CODE REVIEW

**Review by maxneuvians — COMMENTED** [review]
I think this may break local dev? We might want to make this conditional based on env

**Comment by patheard** [comment]
I double checked and everything is working nicely for me locally:
Screenshot 2023-05-11 at 9 03 57 AM

The Mozilla dev docs are also saying this is expected so perhaps it is a newer browser thing to allow it:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

**Review by maxneuvians — APPROVED** [review]
Thank you for checking!

**Review by cgye — COMMENTED** [review]
lgtm

**Pull request merged**
